module.exports = {
  ARI : {name: 'Arizona Diamondbacks',
           teamID: 109,
           teamCode: 'ari',
           fileCode: 'ari'},
  ATL : {name: 'Atlanta Braves',
           teamID: 144,
           teamCode: 'atl',
           fileCode: 'atl'},
  BAL : {name: 'Baltimore Orioles',
           teamID: 110,
           teamCode: 'bal',
           fileCode: 'bal'},
  BOS : {name: 'Boston Red Sox',
           teamID: 111,
           teamCode: 'bos',
           fileCode: 'bos'},
  CHC : {name: 'Chicago Cubs',
           teamID: 112,
           teamCode: 'chn',
           fileCode: 'chc'},
  CWS : {name: 'Chicago White Sox',
           teamID: 145,
           teamCode: 'cha',
           fileCode: 'cws'},
  CIN : {name: 'Cincinnati Reds',
           teamID: 113,
           teamCode: 'cin',
           fileCode: 'cin'},
  CLE : {name: 'Cleveland Indians',
           teamID: 114,
           teamCode: 'cle',
           fileCode: 'cle'},
  COL : {name: 'Colorado Rockies',
           teamID: 115,
           teamCode: 'col',
           fileCode: 'col'},
  DET : {name: 'Detroit Tigers',
           teamID: 116,
           teamCode: 'det',
           fileCode: 'det'},
  HOU : {name: 'Houston Astros',
           teamID: 117,
           teamCode: 'hou',
           fileCode: 'hou'},
  KC : {name: 'Kansas City Royals',
           teamID: 118,
           teamCode: 'kca',
           fileCode: 'kc'},
  LAA : {name: 'Los Angeles Angels',
           teamID: 108,
           teamCode: 'ana',
           fileCode: 'ana'},
  LAD : {name: 'Los Angeles Dodgers',
           teamID: 119,
           teamCode: 'lan',
           fileCode: 'la'},
  MIA : {name: 'Miami Marlins',
           teamID: 146,
           teamCode: 'mia',
           fileCode: 'mia'},
  MIL : {name: 'Milwaukee Brewers',
           teamID: 158,
           teamCode: 'mil',
           fileCode: 'mil'},
  MIN : {name: 'Minnesota Twins',
           teamID: 142,
           teamCode: 'min',
           fileCode: 'min'},
  NYM : {name: 'New York Mets',
           teamID: 121,
           teamCode: 'nyn',
           fileCode: 'nym'},
  NYY : {name: 'New York Yankees',
           teamID: 147,
           teamCode: 'nya',
           fileCode: 'nyy'},
  OAK : {name: 'Oakland Athletics',
           teamID: 133,
           teamCode: 'oak',
           fileCode: 'oak'},
  PHI : {name: 'Philadelphia Phillies',
           teamID: 143,
           teamCode: 'phi',
           fileCode: 'phi'},
  PIT : {name: 'Pittsburgh Pirates',
           teamID: 134,
           teamCode: 'pit',
           fileCode: 'pit'},
  SD : {name: 'San Diego Padres',
           teamID: 135,
           teamCode: 'sdn',
           fileCode: 'sd'},
  SF : {name: 'San Francisco Giants',
           teamID: 137,
           teamCode: 'sfn',
           fileCode: 'sf'},
  SEA : {name: 'Seattle Mariners',
           teamID: 136,
           teamCode: 'sea',
           fileCode: 'sea'},
  STL : {name: 'St. Louis Cardinals',
           teamID: 138,
           teamCode: 'sln',
           fileCode: 'stl'},
  TB : {name: 'Tampa Bay Rays',
           teamID: 139,
           teamCode: 'tba',
           fileCode: 'tb'},
  TEX : {name: 'Texas Rangers',
           teamID: 140,
           teamCode: 'tex',
           fileCode: 'tex'},
  TOR : {name: 'Toronto Blue Jays',
           teamID: 141,
           teamCode: 'tor',
           fileCode: 'tor'},
  WSH : {name: 'Washington Nationals',
           teamID: 120,
           teamCode: 'was',
           fileCode: 'was'}
}
